### ISSUE TITLE
Could not resolve endpoints

### ISSUE THREAD

**Issue by northboys** [ahaenggli/AzureAD-LDAP-wrapper#23]
**Describe the bug**
Mybe not a bug, but i need help for this error.

i got error when start the container.
```
INFO: 2022-07-01T04:23:59.772Z:  server.js refreshDB() func called
INFO: 2022-07-01T04:23:59.776Z:  ldapwrapper.js start
INFO: 2022-07-01T04:23:59.776Z:  ldapwrapper.js mkdirSync: nothing to do
server.js ---->  LDAP server up at:  ldap://0.0.0.0:13389
ERROR: 2022-07-01T04:26:10.863Z:  ldapwrapper.js ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detai
l: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter
.
    at ClientAuthError.AuthError [as constructor] (/app/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:483:24)
    at new ClientAuthError (/app/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:773:28)
    at Function.ClientAuthError.createEndpointDiscoveryIncompleteError (/app/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:810:16)
    at Function.<anonymous> (/app/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:7208:47)
    at step (/app/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:79:23)
    at Object.throw (/app/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:60:53)
    at rejected (/app/node_modules/@azure/msal-node/node_modules/@azure/msal-common/dist/index.cjs.js:51:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errorCode: 'endpoints_resolution_error',
  errorMessage: 'Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is n
ot a trusted authority. Please include this authority in the knownAuthorities config parameter.',
  subError: '',
  correlationId: 'e353e98c-51eb-4bc7-a1d7-7a038183a332'
}
```

**Comment by northboys** [comment]
Sorry my bad, this error come form my proxy...

**Comment by northboys** [comment]
I got another error like this after connected to AzureAD.
```
Gg\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Host: graph.microsoft.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v1.0/users?$select=businessPhones,displayName,givenName,jobTitle,mail,mobilePhone,officeLocation,preferredLanguage,surname,userPrincipalName,id,identities,userType,externalUserState&$filter=userType%20eq%20%27Member%27',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'graph.microsoft.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: { error: [Object] }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
ERROR: 2022-07-01T06:51:57.314Z:  graph_azuread.js callApi-endpoint https://graph.microsoft.com/v1.0/users?$select=businessPhones,displayName,givenName,jobTitle,mail,mobilePhone,officeLocation,preferredLanguage,surname,userPrincipalName,id,identities,userType,externalUserState&$filter=userType%20eq%20'Member'
ERROR: 2022-07-01T06:51:57.314Z:  graph_azuread.js callApi-opts {}
```

**Comment by ahaenggli** [comment]
Thank you for the message. The beginning of the error with hopefully more details is missing. The part should start with something like `ERROR: 2022-07-01T06:51:57.314Z: graph_azuread.js callApi-error`. 

I've only seen an error in this part of the code twice - once on a firewall that blocked access (because of the special $-character in the URL), and once during local testing when I blocked graph.microsoft.com via pihole to test the local cached password hashes.

**Comment by northboys** [comment]
Working fine now after change permission type to Application
<img width="800" alt="Screen Shot 2022-07-04 at 08 47 52" src="https://user-images.githubusercontent.com/38155944/177067764-31ef62d6-9d60-4ebd-8300-a57ff3d25743.png">

**Comment by northboys** [comment]
i got this error when try to use proxy on docker compose.

Container Logs:
```
ERROR: 2022-07-04T02:09:48.621Z:  ldapwrapper.js ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again.
```
Docker compose:
```
    environment:
      HTTP_PROXY: myproxy
      HTTPS_PROXY: myproxy
```

**Comment by ahaenggli** [comment]
It looks like MS has made some improvements in the msal version [1.9.1](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/CHANGELOG.md#191). In production, I am still using msal 1.6.0. 
I will update the dependencies and add the proxy settings in the next release (probably this weekend).

**Comment by northboys** [comment]
Thanks @ahaenggli

**Comment by ahaenggli** [comment]
A first attempt is available in the docker dev tag. It would be great if you could give a try with that? 
The attempt should use the env vars `HTTPS_PROXY` and `HTTP_PROXY`.

**Comment by ahaenggli** [comment]
Great! The new release with proxy support (v1.8.0) should be available in the next few minutes.
