### ISSUE TITLE
Update custom attribute value not affected

### ISSUE THREAD

**Issue by northboys** [ahaenggli/AzureAD-LDAP-wrapper#27]
**Describe the bug**
Mybe not a bug, but i need help for this error.

i got error when try to update custom attribute value using LDAP_BINDUSER (not in AzureAD existing).

my custom attribute:
- Database = mydatabase
- DatabasePermission = UPDATE, CREATE

#### Container Logs
```
INFO: 2022-07-14T03:10:07.209Z:  server.js modify dn uid=myuser,cn=users,dc=example,dc=net
INFO: 2022-07-14T03:10:07.210Z:  server.js modify req.changes [
  Change {
    _modification: Attribute { type: 'database', _vals: [Array] },
    _operation: 0
  },
  Change {
    _modification: Attribute { type: 'database', _vals: [Array] },
    _operation: 1
  }
]
```

Could you add a super user who can create and update custom attributes on the ldap server?.

**Comment by ahaenggli** [comment]
LDAP_BINDUSER is the super user who is allowed to do everything.
Your container log shows that the correct part of the code is reached. 
What error do you get? Is there any way to reproduce the error? 
Unfortunately, my local test just worked...
```powershell
$ldap_server = "127.0.0.1"; # server IP
$ldap_bind   = "uid=root"; # from LDAP_BINDUSER 
$ldap_pass   = "mystrongpw"; # from LDAP_BINDUSER 
$base        = "dc=domain,dc=tld"; 

# Install-Module -Name S.DS.P
Add-Type -AssemblyName System.DirectoryServices.Protocols;

#get password as secure string 
$pwd = ConvertTo-SecureString -String $ldap_pass  -AsPlainText -Force;
$cred = new-object PSCredential($ldap_bind, $pwd);
$Ldap = Get-LdapConnection -LdapServer $ldap_server -Credential $cred -AuthType Basic;

$SearchResults = Find-LdapObject -LdapConnection $Ldap -SearchFilter:"(&(uid=miriamg*)(objectClass=*))" -SearchBase:"cn=users,$($base)" -PropertiesToLoad('Database', 'DatabasePermission');
Write-Output "before:";
Write-Output $SearchResults;

$Props = @{"distinguishedName"=$null;"Database"="notsureyet";"DatabasePermission"=@("UPDATE","INSERT");};
$obj = new-object PSObject -Property $Props;
$obj.DistinguishedName = $SearchResults.distinguishedName;
$obj.Database = "mydatabase";
 
Write-Output "estimated:";
Write-Output $obj;

$obj | Edit-LdapObject -LdapConnection $Ldap -Mode Add;

$SearchResults = Find-LdapObject -LdapConnection $Ldap -SearchFilter:"(&(uid=miriamg*)(objectClass=*))" -SearchBase:"cn=users,$($base)" -PropertiesToLoad('Database', 'DatabasePermission');
Write-Output "check:";
Write-Output $SearchResults;
```
with the output:
![grafik](https://user-images.githubusercontent.com/23347180/179061926-d76f2177-68c4-474c-b1ee-5a5dd75a72c4.png)
the log:
![grafik](https://user-images.githubusercontent.com/23347180/179061988-d2dd2b24-4af9-42ba-9617-233fdf333d75.png)
and the entry in the json file:
![grafik](https://user-images.githubusercontent.com/23347180/179062055-01e1c0d5-94dd-4e19-94bc-177bf4c023cc.png)

**Comment by northboys** [comment]
i got this error when try to update attribute value, but if i add new attribute and value it's working fine.

#### Apache Directory Studio logs
```
Error while executing LDIF
 -  [LDAP result code 1 - operationsError] entry[modType].push is not a function
  org.apache.directory.studio.connection.core.io.StudioLdapException:  [LDAP result code 1 - operationsError] entry[modType].push is not a function
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.toStudioLdapException(DirectoryApiConnectionWrapper.java:1350)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.access$2(DirectoryApiConnectionWrapper.java:1342)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper$4.run(DirectoryApiConnectionWrapper.java:754)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.runAndMonitor(DirectoryApiConnectionWrapper.java:1261)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.checkConnectionAndRunAndMonitor(DirectoryApiConnectionWrapper.java:1209)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.modifyEntry(DirectoryApiConnectionWrapper.java:766)
	at org.apache.directory.studio.ldapbrowser.core.jobs.ImportLdifRunnable.importLdifRecord(ImportLdifRunnable.java:503)
	at org.apache.directory.studio.ldapbrowser.core.jobs.ImportLdifRunnable.importLdif(ImportLdifRunnable.java:272)
	at org.apache.directory.studio.ldapbrowser.core.jobs.ExecuteLdifRunnable.executeLdif(ExecuteLdifRunnable.java:157)
	at org.apache.directory.studio.ldapbrowser.core.jobs.ExecuteLdifRunnable.run(ExecuteLdifRunnable.java:123)
	at org.apache.directory.studio.ldapbrowser.core.jobs.UpdateEntryRunnable.run(UpdateEntryRunnable.java:59)
	at org.apache.directory.studio.connection.ui.RunnableContextRunner$1.run(RunnableContextRunner.java:129)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.apache.directory.api.ldap.model.exception.LdapOperationErrorException: entry[modType].push is not a function
	at org.apache.directory.api.ldap.model.message.ResultCodeEnum.processResponse(ResultCodeEnum.java:2130)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.checkResponse(DirectoryApiConnectionWrapper.java:1337)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper.access$6(DirectoryApiConnectionWrapper.java:1333)
	at org.apache.directory.studio.connection.core.io.api.DirectoryApiConnectionWrapper$4.run(DirectoryApiConnectionWrapper.java:750)
	... 10 more

   [LDAP result code 1 - operationsError] entry[modType].push is not a function

```
#### Container logs
```
```INFO: 2022-07-15T01:33:28.257Z:  server.js modify req.changes [
  Change {
    _modification: Attribute { type: 'database', _vals: [Array] },
    _operation: 0
  },
  Change {
    _modification: Attribute { type: 'database', _vals: [Array] },
    _operation: 1
  }
]

**Comment by ahaenggli** [comment]
Thx! I can reproduce it now and am working on a fix.

**Comment by ahaenggli** [comment]
Seems there was a second problem. When adding something in "CamelCase", it was stored as "camelcase" (all lower case) - should now be be fixed as well. 
A first attempt is available in the docker dev tag again - could you maybe try it out as well?

**Comment by northboys** [comment]
Hii @ahaenggli, I've tried it, it works when I add a new attribute, but when I update the attribute value I can't find it.

#### Container Logs
```
INFO: 2022-07-17T14:31:45.934Z:  server.js server.bind uid=admin,cn=users,dc=example,dc=net
INFO: 2022-07-17T14:31:45.934Z:  server.js server.bind admin binduser, you shall pass
INFO: 2022-07-17T14:31:45.942Z:  server.js server.search Search for => DB: dc=example,dc=net; Scope: base; Filter: (objectclass=*); Attributes: subschemasubentry;
INFO: 2022-07-17T14:31:45.944Z:  server.js server.search searchableEntries NOT modified 65
INFO: 2022-07-17T14:31:45.953Z:  server.js server.search Search for => DB: cn=subschema; Scope: base; Filter: (objectclass=subschema); Attributes: createtimestamp,modifytimestamp;
INFO: 2022-07-17T14:31:45.958Z:  server.js server.search Search for => DB: dc=example,dc=net; Scope: base; Filter: (objectclass=*); Attributes: namingcontexts,subschemasubentry,supportedldapversion,supportedsaslmechanisms,supportedextension,supportedcontrol,supportedfeatures,vendorname,vendorversion,+,objectclass;
INFO: 2022-07-17T14:31:45.961Z:  server.js server.search searchableEntries NOT modified 65
INFO: 2022-07-17T14:31:45.965Z:  server.js server.search Search for => DB: dc=net; Scope: base; Filter: (objectclass=*); Attributes: ;
INFO: 2022-07-17T14:31:45.968Z:  server.js server.search searchableEntries NOT modified 65
INFO: 2022-07-17T14:31:46.014Z:  server.js server.search Search for => DB: dc=example,dc=net; Scope: base; Filter: (objectclass=*); Attributes: ;
INFO: 2022-07-17T14:31:46.020Z:  server.js server.search searchableEntries NOT modified 65
INFO: 2022-07-17T14:31:46.027Z:  server.js server.search Search for => DB: dc=example,dc=net; Scope: base; Filter: (objectclass=*); Attributes: *;
INFO: 2022-07-17T14:31:46.030Z:  server.js server.search searchableEntries NOT modified 65
INFO: 2022-07-17T14:31:46.037Z:  server.js server.search Search for => DB: dc=example,dc=net; Scope: one; Filter: (objectclass=*); Attributes: objectclass;
INFO: 2022-07-17T14:31:46.040Z:  server.js server.search searchableEntries NOT modified 65
INFO: 2022-07-17T14:31:46.049Z:  server.js server.search Search for => DB: cn=subschema; Scope: base; Filter: (objectclass=*); Attributes: ;
INFO: 2022-07-17T14:31:46.086Z:  server.js server.search Search for => DB: cn=subschema; Scope: base; Filter: (objectclass=*); Attributes: hassubordinates,objectclass;
INFO: 2022-07-17T14:31:49.696Z:  server.js server.search Search for => DB: dc=example,dc=net; Scope: base; Filter: (objectclass=*); Attributes: *;
INFO: 2022-07-17T14:31:49.699Z:  server.js server.search searchableEntries NOT modified 65
INFO: 2022-07-17T14:31:50.653Z:  server.js server.search Search for => DB: dc=example,dc=net; Scope: one; Filter: (objectclass=*); Attributes: hassubordinates,objectclass;
INFO: 2022-07-17T14:31:50.658Z:  server.js server.search searchableEntries NOT modified 65
INFO: 2022-07-17T14:31:55.045Z:  server.js server.search Search for => DB: cn=users,dc=example,dc=net; Scope: one; Filter: (objectclass=*); Attributes: hassubordinates,objectclass;
INFO: 2022-07-17T14:31:55.050Z:  server.js server.search searchableEntries NOT modified 65
INFO: 2022-07-17T14:31:58.382Z:  server.js server.search Search for => DB: uid=myuser,cn=users,dc=example,dc=net; Scope: base; Filter: (objectclass=*); Attributes: *;
INFO: 2022-07-17T14:31:58.386Z:  server.js server.search searchableEntries NOT modified 65
INFO: 2022-07-17T14:32:14.638Z:  server.js modify dn uid=myuser,cn=users,dc=example,dc=net
INFO: 2022-07-17T14:32:14.638Z:  server.js modify req.changes [
  Change {
    _modification: Attribute { type: 'database', _vals: [Array] },
    _operation: 0
  }
]
INFO: 2022-07-17T14:32:14.645Z:  server.js server.search Search for => DB: uid=myuser,cn=users,dc=example,dc=net; Scope: base; Filter: (objectclass=*); Attributes: *;
INFO: 2022-07-17T14:32:14.646Z:  server.js server.search searchableEntries NOT modified 64
INFO: 2022-07-17T14:33:04.676Z:  server.js modify dn uid=myuser,cn=users,dc=example,dc=net
INFO: 2022-07-17T14:33:04.676Z:  server.js modify req.changes [
  Change {
    _modification: Attribute { type: 'database', _vals: [Array] },
    _operation: 0
  },
  Change {
    _modification: Attribute { type: 'database', _vals: [Array] },
    _operation: 1
  }
]
INFO: 2022-07-17T14:33:04.680Z:  server.js server.search Search for => DB: uid=myuser,cn=users,dc=example,dc=net; Scope: base; Filter: (objectclass=*); Attributes: *;
INFO: 2022-07-17T14:33:04.682Z:  server.js server.search searchableEntries NOT modified 64
```

**Comment by ahaenggli** [comment]
It looks like delete (_operation: 1) wrongly removes the entire attribute and not just the selected value(s).
Since delete (_operation: 1) is in the same request as add (_operation: 0), there is nothing left.... A next attempt is available in the docker dev tag again.

**Comment by northboys** [comment]
Thanks @ahaenggli its working...
